const gists = {
  GET_GISTS_REQUEST: "GET_GISTS_REQUEST",
  GET_GISTS_SUCCESS: "GET_GISTS_SUCCESS",
  GET_GISTS_FAILED: "GET_GISTS_FAILED",


  GET_GIST_BY_ID_REQUEST: "GET_GIST_BY_ID_REQUEST",
  GET_GIST_BY_ID_SUCCESS: "GET_GIST_BY_ID_SUCCESS",
  GET_GIST_BY_ID_FAILED: "GET_GIST_BY_ID_FAILED",
};

export default gists


